//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ardis.TestWeblate.Components.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ardis.TestWeblate.Components.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Ardis_TestWeblate_Components_Car_brand_Description {
            get {
                return ResourceManager.GetString("Ardis_TestWeblate_Components_Car_brand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the brand of the car with pull request.
        /// </summary>
        public static string Ardis_TestWeblate_Components_Car_brand_Name {
            get {
                return ResourceManager.GetString("Ardis_TestWeblate_Components_Car_brand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Ardis_TestWeblate_Components_Car_color_Description {
            get {
                return ResourceManager.GetString("Ardis_TestWeblate_Components_Car_color_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the color.
        /// </summary>
        public static string Ardis_TestWeblate_Components_Car_color_Name {
            get {
                return ResourceManager.GetString("Ardis_TestWeblate_Components_Car_color_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Ardis_TestWeblate_Components_Car_numberOfDoors_Description {
            get {
                return ResourceManager.GetString("Ardis_TestWeblate_Components_Car_numberOfDoors_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the numbers of doors.
        /// </summary>
        public static string Ardis_TestWeblate_Components_Car_numberOfDoors_Name {
            get {
                return ResourceManager.GetString("Ardis_TestWeblate_Components_Car_numberOfDoors_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Ardis_TestWeblate_Components_Person_adress_Description {
            get {
                return ResourceManager.GetString("Ardis_TestWeblate_Components_Person_adress_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the adress.
        /// </summary>
        public static string Ardis_TestWeblate_Components_Person_adress_Name {
            get {
                return ResourceManager.GetString("Ardis_TestWeblate_Components_Person_adress_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Ardis_TestWeblate_Components_Person_age_Description {
            get {
                return ResourceManager.GetString("Ardis_TestWeblate_Components_Person_age_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the age .
        /// </summary>
        public static string Ardis_TestWeblate_Components_Person_age_Name {
            get {
                return ResourceManager.GetString("Ardis_TestWeblate_Components_Person_age_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Ardis_TestWeblate_Components_Person_city_Description {
            get {
                return ResourceManager.GetString("Ardis_TestWeblate_Components_Person_city_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the city.
        /// </summary>
        public static string Ardis_TestWeblate_Components_Person_city_Name {
            get {
                return ResourceManager.GetString("Ardis_TestWeblate_Components_Person_city_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Ardis_TestWeblate_Components_Person_name_Description {
            get {
                return ResourceManager.GetString("Ardis_TestWeblate_Components_Person_name_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the name.
        /// </summary>
        public static string Ardis_TestWeblate_Components_Person_name_Name {
            get {
                return ResourceManager.GetString("Ardis_TestWeblate_Components_Person_name_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retest auto commit/push - new.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test auto update.
        /// </summary>
        public static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
    }
}
